spring:
  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  profiles:
    include: oauth,aws

  session:
    store-type: jdbc

logging:
  level:
    org.springframework: INFO
    me.seolnavy.study: DEBUG